FROM ubuntu:18.04
MAINTAINER Yangyang Fu <yangyang.fu@colorado.edu>

# Revision numbers from svn
ENV REV_JMODELICA 12903
ENV REV_ASSIMULO 873

# Set environment variables
ENV SRC_DIR /usr/local/src
ENV MODELICAPATH /usr/local/JModelica/ThirdParty/MSL

# Avoid warnings
# debconf: unable to initialize frontend: Dialog
# debconf: (TERM is not set, so the dialog frontend is not usable.)
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections


# install python and python packages
RUN	apt-get update && \
	apt-get install -y \
	python3-pip \
	python-pip \
	python3-dev \
	libatlas-base-dev \
	gfortran \
	libffi-dev \
	libfreetype6-dev \
	cmake \
	wget \
	unzip

RUN	pip3 install --upgrade numpy \
    scipy \
    nose \
    pandas \
    matplotlib \
    sympy \	
    jupyter \
    pytest \
    Cython \
    lxml 
    
### Install PyFMI
# Install FMI
RUN mkdir $SRC_DIR/pyfmi  && \
	cd $SRC_DIR/pyfmi && \
	wget http://www.jmodelica.org/FMILibrary/FMILibrary-2.0.3-src.zip && \
	unzip FMILibrary-2.0.3-src.zip && \
	cd FMILibrary-2.0.3/ && \
    mkdir build-fmilib && \
    cd build-fmilib && \
    cmake -DFMILIB_INSTALL_PREFIX=../install ../ &&\
    make install test 

# Install Sundials
RUN	cd $SRC_DIR/pyfmi && \
	wget http://computation.llnl.gov/projects/sundials-suite-nonlinear-differential-algebraic-equation-solvers/download/sundials-2.4.0.tar.gz && \
	tar xzf sundials-2.4.0.tar.gz && \
	cd sundials-2.4.0 && \
	./configure CFLAGS="-fPIC" && \
	make install
	
# Install Assimulo
RUN	cd $SRC_DIR/pyfmi && \
	wget https://pypi.python.org/packages/4c/c0/19a54949817204313efff9f83f1e4a247edebed0a1cc5a317a95d3f374ae/Assimulo-2.9.zip && \
 	unzip Assimulo-2.9.zip && \
	cd Assimulo-2.9 && \
    python3 setup.py install --sundials-home=/usr/local/ --blas-home=/usr/lib/x86_64-linux-gnu/ --lapack-home=/usr/lib/x86_64-linux-gnu/ --log=DEBUG

# Install PyFMI
RUN	cd $SRC_DIR/pyfmi && \
	wget https://pypi.python.org/packages/66/60/26664b2b2cad4a7fae409214e2f8901177322d78bfb11ef61e580115c9b8/PyFMI-2.3.1.zip#md5=577829ee1ee83fbb8c28ddf4b82aa4ee && \
	unzip PyFMI-2.3.1.zip && \
	cd PyFMI-2.3.1 && \
	python3 setup.py install --fmil-home=$SRC_DIR/pyfmi/FMILibrary-2.0.3/install/ && \
	pip3 install pyfmi

### Install OpenAI gym with libav-tools for visualization purposes
RUN apt-get update && \
	apt-get install -y ffmpeg && \
	pip install gym && \
	pip3 install pyglet

### Install java 8
RUN apt install -y openjdk-8-jdk

	   
# Install required packages for JModelica


# Avoid warning that Matplotlib is building the font cache using fc-list. This may take a moment.
# This needs to be towards the end of the script as the command writes data to
# /home/developer/.cache

RUN export uid=1000 gid=1000 && \
    mkdir -p /home/developer && \
    mkdir -p /etc/sudoers.d && \
    echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown ${uid}:${gid} -R /home/developer

#RUN mkdir /home/developer
USER developer
ENV HOME /home/developer